name: HF Spaces Deployment
on:
  push:
    branches: [main]

  # to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  sync-to-hub:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          lfs: true
      
      - name: Fetch LFS objects
        run: git lfs fetch --all
      
      - name: Push to hub
        env:
          HF_TOKEN: ${{ secrets.LEADERBOARD_GITHUB_DEPLOYMENT }}
        run: |
          git lfs install
          git remote add hf https://huggingface.co/spaces/gperdrizet/leaderboard
          git config --local credential.helper '!f() { echo "username=gperdrizet"; echo "password=$HF_TOKEN"; }; f'
          git lfs push --all hf
          git push --force hf main